kind: pipeline
name: default

volumes:
  - name: cache
    temp: {}

steps:
  - name: build_prod
    image: plugins/docker
    volumes:
      - name: cache
        path: /var/lib/docker
    settings:
      tags:
        - "${DRONE_COMMIT_SHA:0:7}"
        - latest
      repo: uccnetsoc/drone-ansible
      dockerfile: docker/Dockerfile.linux.amd64
      registry: docker.io
      custom_dns: [1.1.1.1]
      username:
        from_secret: docker_hub_user
      password:
        from_secret: docker_hub_token
    when:
      event:
        - push
      branch:
        - master

  - name: discord_notif_success
    image: appleboy/drone-discord
    environment:
      WEBHOOK_ID:
        from_secret: discord_webhook_id
      WEBHOOK_TOKEN:
        from_secret: discord_webhook_token
    settings:
      username: Netsoc CI
      avatar_url: https://raw.githubusercontent.com/drone/brand/3051b0d85318a2a20b62927ba19fc07e24c0d751/logos/png/white/drone-logo-png-white-256.png
      color: "#42f483"
      message: discord-bot successfully built and pushed. Build num {{build.number}}. {{build.link}}
    when:
      event:
        - push
      branch:
        - master
      status:
        - success

  - name: discord_notif_failure
    image: appleboy/drone-discord
    environment:
      WEBHOOK_ID:
        from_secret: discord_webhook_id
      WEBHOOK_TOKEN:
        from_secret: discord_webhook_token
    settings:
      username: Netsoc CI
      avatar_url: https://raw.githubusercontent.com/drone/brand/3051b0d85318a2a20b62927ba19fc07e24c0d751/logos/png/white/drone-logo-png-white-256.png
      color: "#e04414"
      message: drone-ansible failed. Build num {{build.number}}. {{build.link}}
    when:
      event:
        - push
      branch:
        - master
      status:
        - failure
